<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_JetWooBuilder</name>
   <tag></tag>
   <elementGuidId>3e2cd37b-9f43-4184-abd4-2e16aae8d92b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='mainform']/nav/a[10]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3746afd0-4c43-499c-9013-76064581284e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://test2.bittermate.com/wp-admin/admin.php?page=wc-settings&amp;tab=jet-woo-builder-settings</value>
      <webElementGuid>8259ca68-99e0-4d10-ba55-4e5d2aebd577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-tab </value>
      <webElementGuid>1f0c38a6-5ca5-43fe-82e4-b10d4c559849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JetWooBuilder</value>
      <webElementGuid>50ee6a50-9d93-441a-84cc-e6ae8a4b474c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainform&quot;)/nav[@class=&quot;nav-tab-wrapper woo-nav-tab-wrapper&quot;]/a[@class=&quot;nav-tab&quot;]</value>
      <webElementGuid>14a51136-1359-405c-8bc8-7d812c6d0eea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='mainform']/nav/a[10]</value>
      <webElementGuid>313354a0-e1ba-46b1-bb94-b99a580ac3e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'JetWooBuilder')])[2]</value>
      <webElementGuid>b2bebd1e-ce08-4a6c-9a9d-df2f23848ad1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Multi-currency'])[1]/following::a[1]</value>
      <webElementGuid>79be5ce9-8fe9-4d46-91b2-72e40affa2df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Advanced'])[1]/following::a[2]</value>
      <webElementGuid>e846fabf-f9f9-4d92-9e70-13b7c642e525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='General'])[4]/preceding::a[1]</value>
      <webElementGuid>78c49a9f-f93a-4903-83db-298d9fddda11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Give Feedback'])[1]/preceding::a[3]</value>
      <webElementGuid>d2095fa2-36a4-4f7e-9cbf-0fbcf7db6e91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='JetWooBuilder']/parent::*</value>
      <webElementGuid>cc8b05df-bb39-4d83-871c-a9429808e5a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://test2.bittermate.com/wp-admin/admin.php?page=wc-settings&amp;tab=jet-woo-builder-settings')]</value>
      <webElementGuid>f654331c-899e-4ca2-86c5-cd5be62d4350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[10]</value>
      <webElementGuid>475cb7fe-6fe4-47ed-823b-1f43c5712d4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://test2.bittermate.com/wp-admin/admin.php?page=wc-settings&amp;tab=jet-woo-builder-settings' and (text() = 'JetWooBuilder' or . = 'JetWooBuilder')]</value>
      <webElementGuid>37d57d7a-beb1-4d9c-acd5-96c2004a5757</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
