<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_WooCommerce</name>
   <tag></tag>
   <elementGuidId>78c9fdd8-1b92-4bbb-8414-2a55d847e787</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='toplevel_page_woocommerce']/a/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.wp-has-submenu.wp-not-current-submenu.menu-top.toplevel_page_woocommerce.menu-top-first > div.wp-menu-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ec1c8cff-6fbf-4151-b19e-24c781eee3fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wp-menu-name</value>
      <webElementGuid>8ea224a4-2ff7-468d-804e-73f45568892c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>WooCommerce</value>
      <webElementGuid>e2a09c39-1485-44ce-8d76-d262dc2232ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toplevel_page_woocommerce&quot;)/a[@class=&quot;wp-has-submenu wp-not-current-submenu menu-top toplevel_page_woocommerce menu-top-first&quot;]/div[@class=&quot;wp-menu-name&quot;]</value>
      <webElementGuid>290e3315-f292-4ac6-a3e9-4f12e2daedd2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='toplevel_page_woocommerce']/a/div[3]</value>
      <webElementGuid>67a48af9-eb05-4888-a35e-b941afe74b6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add New'])[3]/following::div[9]</value>
      <webElementGuid>3a754a30-63af-458a-813a-fd634fa71cb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Orders'])[1]/preceding::div[1]</value>
      <webElementGuid>da0d3893-16a5-4469-ab13-072bdafb2965</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='WooCommerce']/parent::*</value>
      <webElementGuid>fe2f7c9c-1379-4bc8-8339-aa68dd32aaf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/a/div[3]</value>
      <webElementGuid>5331310b-a170-4cc7-bb2c-20da9cc69c13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'WooCommerce' or . = 'WooCommerce')]</value>
      <webElementGuid>b8c0df86-e77e-4573-b8ec-bf99ea93baa6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
