<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_General</name>
   <tag></tag>
   <elementGuidId>2249914a-42b9-4b9a-9859-2428c215fca0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='mainform']/h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mainform > h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>b4bff407-abec-4b38-88ae-fe04c45cf423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>General</value>
      <webElementGuid>02a3d1c0-c227-4ddc-8df8-aeb54a931265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainform&quot;)/h2[1]</value>
      <webElementGuid>9dfe95f2-7827-47e1-9e05-59d8890a1c36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='mainform']/h2</value>
      <webElementGuid>137d9851-4da0-4817-9fb0-8b5b46315397</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No thanks'])[2]/following::h2[1]</value>
      <webElementGuid>c0bcaab7-f4cf-4b13-bdcc-b42083492a9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Sure! I', &quot;'&quot;, 'd love to help')])[1]/following::h2[1]</value>
      <webElementGuid>83f6c72d-79e0-4881-ab36-2d061727b789</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Widgets Render Method'])[1]/preceding::h2[1]</value>
      <webElementGuid>7f94286c-b483-4915-b66f-2f1eca38e222</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/h2</value>
      <webElementGuid>460afc14-f5a4-4f49-863e-33a53dbac182</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'General' or . = 'General')]</value>
      <webElementGuid>eb8223c0-898b-42cd-91a0-7e5195eb184d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
