<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Thank You Page</name>
   <tag></tag>
   <elementGuidId>1ee1be2c-af7b-4159-9161-3bdc541da32e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='mainform']/h2[8]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>dab850f2-0ab5-479a-ab6f-0ee8041d29b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thank You Page</value>
      <webElementGuid>16dc9e9d-c514-4fb9-ab86-e650938b2d26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainform&quot;)/h2[8]</value>
      <webElementGuid>67c8c43d-7197-4c50-b74e-eed0d35cf081</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='mainform']/h2[8]</value>
      <webElementGuid>1e7c5e6b-60dc-4f60-82db-f5bcd69d6e50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[13]/following::h2[1]</value>
      <webElementGuid>d37bfef6-b4fa-4690-af1c-2bf172a63368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Custom Thank You Page'])[1]/preceding::h2[1]</value>
      <webElementGuid>661303bf-ab07-4d80-937e-ca6726004b5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Custom Thank You Page'])[2]/preceding::h2[1]</value>
      <webElementGuid>69b52c33-1532-4332-9975-492371ee9843</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Thank You Page']/parent::*</value>
      <webElementGuid>4c95d1a1-23b7-4712-9286-85dfcae73e3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2[8]</value>
      <webElementGuid>6baebe83-a5df-4442-87a9-ec77e73a9658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Thank You Page' or . = 'Thank You Page')]</value>
      <webElementGuid>9679e54f-c5a2-426f-920b-f83af0b0ad85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
