<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>th_Widgets Render Method</name>
   <tag></tag>
   <elementGuidId>72054070-72d4-4bbd-b4c4-69b1742e2b50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='mainform']/table/tbody/tr/th</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>th.titledesc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>6f2b5405-d135-460e-aecd-7f1c8d1b26e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scope</name>
      <type>Main</type>
      <value>row</value>
      <webElementGuid>04ce7d77-244c-455f-b9b6-faba6a07a68b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>titledesc</value>
      <webElementGuid>14c503cf-f076-4d32-91ab-aa295b5f770a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Widgets Render Method</value>
      <webElementGuid>fe43a314-71c1-49be-a860-b4023d4bc08e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainform&quot;)/table[@class=&quot;form-table&quot;]/tbody[1]/tr[@class=&quot;render_method&quot;]/th[@class=&quot;titledesc&quot;]</value>
      <webElementGuid>866957e8-a35e-40e2-9bfc-b3578a9ba2dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='mainform']/table/tbody/tr/th</value>
      <webElementGuid>2615b3bd-9f83-40a1-be23-677a9bb08a2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='General'])[3]/following::th[1]</value>
      <webElementGuid>57037ccd-3ea4-4508-b631-a3dcc43fb382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No thanks'])[2]/following::th[1]</value>
      <webElementGuid>86803cbc-232a-4270-957b-1f39e4247b38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/preceding::th[1]</value>
      <webElementGuid>7a6c1ea4-8634-41a4-be25-37cc6aaaa3d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Widgets Render Method']/parent::*</value>
      <webElementGuid>770f7268-e09f-43c4-a9f8-37af1aadb432</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th</value>
      <webElementGuid>e4ce114d-24a1-4d2f-8e10-895eb01e5a84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'Widgets Render Method' or . = 'Widgets Render Method')]</value>
      <webElementGuid>47d90637-73a7-4b1d-9b39-b6256764dc29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
