<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bulk action_button</name>
   <tag></tag>
   <elementGuidId>df098055-3ff4-43fd-9d95-9e6660f8ea04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='doaction']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#doaction</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4027eb0a-b6ea-4ca0-8d73-da88f0603ca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>3371696f-2ea5-4cdc-be98-eabca23e0932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>doaction</value>
      <webElementGuid>abe18dcf-8cc1-45d8-ac0e-9c13604dce6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button action</value>
      <webElementGuid>72570521-1115-4347-8097-e121b13e5805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Apply</value>
      <webElementGuid>395c399b-cfbb-4a57-879a-b43a34b57838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;doaction&quot;)</value>
      <webElementGuid>5de0b6a8-c243-486c-95a1-1fe640631dfc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='doaction']</value>
      <webElementGuid>270d33b2-eb38-4527-b00b-e5274ea16345</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wp-mail-smtp']/div/div[4]/form/div/div/input</value>
      <webElementGuid>876469b3-ba0f-4e9b-8701-2ddb7e2f8729</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>9dda94ad-d648-4172-ab56-548cec513d3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'doaction']</value>
      <webElementGuid>9713d3d8-adfe-4f84-9447-6d00edcaeaa7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
