<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select all_logs</name>
   <tag></tag>
   <elementGuidId>e8ab325e-2884-4778-87aa-4e13f7d2fce1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cb-select-all-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cb-select-all-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b53b2701-5820-4abc-a3ef-069246ace5b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cb-select-all-1</value>
      <webElementGuid>cf39c5d2-6f24-4f4b-aad9-c3b7d6194eb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>44b982f3-6b50-4ab4-b503-406f533c2c3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cb-select-all-1&quot;)</value>
      <webElementGuid>767d3d56-3d21-41d3-8812-f38723a65a59</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cb-select-all-1']</value>
      <webElementGuid>f81fb5d6-7b40-4dd8-bc56-cd4c09b3ed56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='cb']/input</value>
      <webElementGuid>d29a3592-db10-4d22-a145-222f2e181a34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>c42c3f06-a4ea-4545-bd44-3cba030e3c07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cb-select-all-1' and @type = 'checkbox']</value>
      <webElementGuid>49af89c8-c6dd-4c72-9320-5b0439ae4bc7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
