<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_No emails have been logged for now</name>
   <tag></tag>
   <elementGuidId>702e727a-4390-484a-97ba-386cd2b130b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='the-list']/tr/td</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.colspanchange</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>2957d59f-ff77-459d-9522-25409a878793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>colspanchange</value>
      <webElementGuid>f1ea0bd3-bfcf-49c7-bf24-d15dbd5b268f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>0d6ea32d-e96d-4dd5-af78-591fb5efaefb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No emails have been logged for now.</value>
      <webElementGuid>b3ee72b5-b300-4962-85db-ed6f6227de7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;the-list&quot;)/tr[@class=&quot;no-items&quot;]/td[@class=&quot;colspanchange&quot;]</value>
      <webElementGuid>e6d8e2dd-284b-4a83-ad72-9a160a24a0c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='the-list']/tr/td</value>
      <webElementGuid>a1643109-d6b6-402f-a329-ed44da90858b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date Sent'])[2]/following::td[1]</value>
      <webElementGuid>73564981-f30d-476c-a0e8-ea7f20c61f18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clicked'])[2]/following::td[1]</value>
      <webElementGuid>b07faf20-5307-4e0b-bf3c-224970b0cb75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select all'])[2]/preceding::td[1]</value>
      <webElementGuid>04dde0ee-21e9-474a-aeb1-93ec83167273</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subject'])[3]/preceding::td[2]</value>
      <webElementGuid>a339782e-ed70-4aa6-8b0c-6fafaac5a308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='No emails have been logged for now.']/parent::*</value>
      <webElementGuid>763d7ee4-d25f-4b90-bc64-f757ddc256c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody/tr/td</value>
      <webElementGuid>c610bc4a-8ee1-4a61-9571-e52d6b23a412</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'No emails have been logged for now.' or . = 'No emails have been logged for now.')]</value>
      <webElementGuid>92cb24ef-23a4-450c-bc0f-b2053de404a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
