<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Payments</name>
   <tag></tag>
   <elementGuidId>a2c79f98-9add-4df5-ada6-fb1be464970e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='mainform']/nav/a[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bdf09c60-c445-4c26-9e35-e558b2f27e92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://test2.bittermate.com/wp-admin/admin.php?page=wc-settings&amp;tab=checkout</value>
      <webElementGuid>fd9f14a2-b26e-4dca-9c2f-a8ec1fe5802e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-tab </value>
      <webElementGuid>aa75afaa-8c59-4ebf-8b18-6fdc3a7c4242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Payments</value>
      <webElementGuid>99c29886-ec85-43a7-90d4-1ef1c236f77d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainform&quot;)/nav[@class=&quot;nav-tab-wrapper woo-nav-tab-wrapper&quot;]/a[@class=&quot;nav-tab&quot;]</value>
      <webElementGuid>abffc18a-6de8-4f9e-9395-7286f8d68018</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='mainform']/nav/a[4]</value>
      <webElementGuid>1d0207a6-4a72-41fb-9f9f-813d1f1f4330</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Payments')]</value>
      <webElementGuid>7c5427fe-e85b-47a6-a400-194418441337</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shipping'])[1]/following::a[1]</value>
      <webElementGuid>bf6f71df-55ad-400c-bda0-2cc46dc41cef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Products'])[4]/following::a[2]</value>
      <webElementGuid>4d0757e3-5d5c-41d0-9cfc-725f725988e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accounts &amp; Privacy'])[1]/preceding::a[1]</value>
      <webElementGuid>7367aaeb-d8b7-4db5-8e7b-96dc3c95bae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Emails'])[1]/preceding::a[2]</value>
      <webElementGuid>3744a237-41d3-479a-bdc3-035fd878f661</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://test2.bittermate.com/wp-admin/admin.php?page=wc-settings&amp;tab=checkout')]</value>
      <webElementGuid>7e3160db-5826-4577-a1e3-24a4dbc73c09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]</value>
      <webElementGuid>aff9d74d-2048-4003-8408-238275660771</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://test2.bittermate.com/wp-admin/admin.php?page=wc-settings&amp;tab=checkout' and (text() = 'Payments' or . = 'Payments')]</value>
      <webElementGuid>3d6d11f1-6325-4b63-812c-e8d0ae79ff07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
