<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save changes</name>
   <tag></tag>
   <elementGuidId>61f5ceee-53ee-4a21-84db-84616a77e48e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='save']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;save&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d747603a-2488-49eb-985b-3601209760b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>save</value>
      <webElementGuid>d5d4ce20-35b7-41ad-94ec-6815cb07ca7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-primary woocommerce-save-button</value>
      <webElementGuid>8065719e-95ad-4aae-a2b7-47abec3b085a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>1566dce0-e36d-454a-a1c7-04030f6ce996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save changes</value>
      <webElementGuid>7b7eeae7-0085-415a-99a4-d1136d8cdea3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save changes</value>
      <webElementGuid>68491bea-71da-42bb-96d7-a45676ba6034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainform&quot;)/p[@class=&quot;submit&quot;]/button[@class=&quot;button-primary woocommerce-save-button&quot;]</value>
      <webElementGuid>14066ce6-c366-498a-9cab-7132eeabdf32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='save']</value>
      <webElementGuid>44ce92ee-a035-4d56-8121-655b89212c27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='mainform']/p/button</value>
      <webElementGuid>d03fd140-380a-42ad-ae5c-27ef22c807b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Other payment methods'])[1]/following::button[1]</value>
      <webElementGuid>0955880f-3713-49ac-9bd0-08ff10d6f607</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Set up'])[11]/following::button[1]</value>
      <webElementGuid>e39b38a3-6c8c-43c5-8cfc-cc4994b70e42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WooCommerce'])[3]/preceding::button[1]</value>
      <webElementGuid>56967093-7981-4a9d-807d-db4bc026f5d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='★★★★★'])[1]/preceding::button[1]</value>
      <webElementGuid>fd53ef0f-aa20-4867-bd97-b47020e59b35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save changes']/parent::*</value>
      <webElementGuid>48b692a3-b536-43eb-9d32-6d93c2d6c717</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/button</value>
      <webElementGuid>3049cbdf-5b48-409e-afe3-01b15b027a1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'save' and @type = 'submit' and (text() = 'Save changes' or . = 'Save changes')]</value>
      <webElementGuid>722ac7c3-d476-4d20-8ab4-ed5dffc2f9b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
