<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_WooCommerce</name>
   <tag></tag>
   <elementGuidId>ec9c1b5a-fc35-4525-9ab1-8f6c51ce2f45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='toplevel_page_woocommerce']/a/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.wp-has-submenu.wp-not-current-submenu.menu-top.toplevel_page_woocommerce.menu-top-first > div.wp-menu-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>22edd6fc-ff4c-41b9-bb82-acb414022f6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wp-menu-name</value>
      <webElementGuid>cdb44788-f9d8-4991-93b6-081ab8248b58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>WooCommerce</value>
      <webElementGuid>f5b7fec3-804b-4b09-a8a7-8eadf50a0bb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toplevel_page_woocommerce&quot;)/a[@class=&quot;wp-has-submenu wp-not-current-submenu menu-top toplevel_page_woocommerce menu-top-first&quot;]/div[@class=&quot;wp-menu-name&quot;]</value>
      <webElementGuid>ef035744-5903-4886-a208-8303706910ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='toplevel_page_woocommerce']/a/div[3]</value>
      <webElementGuid>b8471973-0e86-4f90-9d2a-079eb5681bdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add New'])[3]/following::div[9]</value>
      <webElementGuid>66f2f73a-e942-40ef-bcca-5c7081d6a43a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Orders'])[1]/preceding::div[1]</value>
      <webElementGuid>586c8ebd-c406-4813-a820-d5323ef40265</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='WooCommerce']/parent::*</value>
      <webElementGuid>993a901e-7ac4-4767-80a3-a3d26a2daf85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/a/div[3]</value>
      <webElementGuid>73d72273-e268-4630-ab1e-a4bea8cee38c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'WooCommerce' or . = 'WooCommerce')]</value>
      <webElementGuid>f15d0d74-2137-445a-8bfe-a89713798d35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
