<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Select all_cb-select-all-1</name>
   <tag></tag>
   <elementGuidId>7f48015b-e121-49b2-b5cb-1233d227aca7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cb-select-all-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cb-select-all-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>af24e2a3-cf5f-4dc9-a117-abbde5abcf96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cb-select-all-1</value>
      <webElementGuid>65a43c25-59e5-430a-8098-b22d15237185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e03022af-20a8-480b-8b0e-5d4e67a9babf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cb-select-all-1&quot;)</value>
      <webElementGuid>4879cf1b-39e3-4a76-b8a0-2d8208ba32fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cb-select-all-1']</value>
      <webElementGuid>1a3f21ab-eef3-442d-8e58-6ea2dafc4185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='cb']/input</value>
      <webElementGuid>0568f173-5d4d-4729-9ecf-c108f742bfe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>eadb17b2-7c75-421e-9bd4-f3d25b573a51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cb-select-all-1' and @type = 'checkbox']</value>
      <webElementGuid>65a9886c-ca47-482a-bde4-8d8e1e4ccd71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
