<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_HeK7efHMQ5uFnm9JjsPr</name>
   <tag></tag>
   <elementGuidId>67fe469c-5e74-4eea-8c47-6dae2a534f01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='wp-admin-bar-my-account']/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.display-name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f0b3f6d2-4c83-4471-8408-1cd9d509cac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>display-name</value>
      <webElementGuid>5e09a0db-eafa-4c17-958e-1030ff990437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HeK7efHMQ5uFnm9JjsPr</value>
      <webElementGuid>21d494cb-d868-4fdf-b6a1-0b403ae2e3bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wp-admin-bar-my-account&quot;)/a[@class=&quot;ab-item&quot;]/span[@class=&quot;display-name&quot;]</value>
      <webElementGuid>f8e96bc2-dd2c-44b8-908e-b69b1ac345c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='wp-admin-bar-my-account']/a/span</value>
      <webElementGuid>8bda094d-345a-400c-a5b3-00539a6338d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Settings'])[9]/following::span[1]</value>
      <webElementGuid>52c81da6-adba-49ea-8bc0-03418a6e0526</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HeK7efHMQ5uFnm9JjsPr'])[2]/preceding::span[1]</value>
      <webElementGuid>688a2947-18bb-4119-a1a0-ecadfb7ab23d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Profile'])[1]/preceding::span[2]</value>
      <webElementGuid>dd16ae5f-fb2f-494e-b404-9b7b967955b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='HeK7efHMQ5uFnm9JjsPr']/parent::*</value>
      <webElementGuid>eadd7387-8c3d-4db5-ad35-ca01541dbc39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/ul[2]/li/a/span</value>
      <webElementGuid>9c7057de-4d69-4f96-92b3-1687e1eae64f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'HeK7efHMQ5uFnm9JjsPr' or . = 'HeK7efHMQ5uFnm9JjsPr')]</value>
      <webElementGuid>4f97520b-bba2-4f87-99bc-91cb0b5cc961</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
