<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Book now_turitop_booking_system_gift_checkbox</name>
   <tag></tag>
   <elementGuidId>5b13e01d-d873-4ed0-a3ce-9595cbb78ed2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='turitop_booking_system_gift_checkbox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#turitop_booking_system_gift_checkbox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3a1b911c-4d81-404b-8f57-cbe84fc5cbc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>9abe6f12-f9c0-40e3-9e56-8967a43b3ebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>turitop_booking_system_gift_checkbox</value>
      <webElementGuid>898a74e1-eb2b-4b1d-b272-be6eb00d88e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>1d261700-5b81-4050-8ebe-2a0fabb03f14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>turitop_booking_system_gift_checkbox</value>
      <webElementGuid>3c89c9ae-cc5a-421e-a431-2d0e506e75a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;turitop_booking_system_gift_checkbox&quot;)</value>
      <webElementGuid>19bd291f-8692-4340-831f-9d176756596d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='turitop_booking_system_gift_checkbox']</value>
      <webElementGuid>32385a75-d942-4c96-8451-fefd81258969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label/input</value>
      <webElementGuid>fa42d02f-d213-40a6-b67d-38b11e50b2c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'turitop_booking_system_gift_checkbox' and @id = 'turitop_booking_system_gift_checkbox']</value>
      <webElementGuid>785e7d7f-54c1-4788-adb1-f7d0847adaa4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
