<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Book now_turitop_booking_system_gift__a3678f</name>
   <tag></tag>
   <elementGuidId>4cbeeada-7817-4365-b9cb-beb1eb639ff1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='turitop_booking_system_gift_checkbox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#turitop_booking_system_gift_checkbox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>429c7f5f-34d0-41f5-9492-de5cefba72c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b53effd5-eefa-4050-b7cc-54b7e830eec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>turitop_booking_system_gift_checkbox</value>
      <webElementGuid>0e108ba2-32f6-46c4-ad81-567f207395ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>89bc8dfe-d8e3-41e2-91e6-35b9aeafe5f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>turitop_booking_system_gift_checkbox</value>
      <webElementGuid>248ed31e-8136-4717-9d8c-25673ed702e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;turitop_booking_system_gift_checkbox&quot;)</value>
      <webElementGuid>bf184ee0-0a80-4b65-bb7f-62fdf46a6860</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='turitop_booking_system_gift_checkbox']</value>
      <webElementGuid>4c462252-370c-47ac-a5db-bc7568ac2f14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label/input</value>
      <webElementGuid>54b4097f-bedd-4298-b9d7-7d6720af41f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'turitop_booking_system_gift_checkbox' and @id = 'turitop_booking_system_gift_checkbox']</value>
      <webElementGuid>0b075ccb-74f6-4b3b-9a7e-31a7d597483d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
