<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__turitop_booking_system_gift_voucher__734c47</name>
   <tag></tag>
   <elementGuidId>6c5f43ad-d8d6-415d-8d3d-dca3ae2edc04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='turitop_booking_system_gift_voucher_recipient_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#turitop_booking_system_gift_voucher_recipient_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4c284cdb-335d-4454-bdb9-410a35699e62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>037519dc-0456-4c05-92e0-594a12474c08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>turitop_booking_system_gift_voucher_recipient_name</value>
      <webElementGuid>c778abb8-be63-4f77-8451-ae13f9ad33ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>turitop_booking_system_gift_voucher_recipient_name</value>
      <webElementGuid>2de331aa-95dc-41df-a349-3505be41f4aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;turitop_booking_system_gift_voucher_recipient_name&quot;)</value>
      <webElementGuid>dabe6866-8cf9-42c1-ac12-a6353915975e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='turitop_booking_system_gift_voucher_recipient_name']</value>
      <webElementGuid>16a36c55-0a48-418b-845f-66071f7d67f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div[2]/label/input</value>
      <webElementGuid>4e98ac0e-0216-434e-82a0-28cacde22fc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'turitop_booking_system_gift_voucher_recipient_name' and @id = 'turitop_booking_system_gift_voucher_recipient_name']</value>
      <webElementGuid>708c2335-aee0-4e37-a903-02868bc1b79a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
