<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__turitop_booking_system_gift_voucher__7a3023</name>
   <tag></tag>
   <elementGuidId>0eaabcd3-9344-41aa-b0f6-76354bfd68ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='turitop_booking_system_gift_voucher_recipient_email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#turitop_booking_system_gift_voucher_recipient_email</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7362bbca-46bb-4445-b6eb-00518ca7e834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ba42f64d-f526-4406-b89c-9728b61ac902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>turitop_booking_system_gift_voucher_recipient_email</value>
      <webElementGuid>1cf0790f-8a55-4f96-9bc7-0175c662ed81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>turitop_booking_system_gift_voucher_recipient_email</value>
      <webElementGuid>63887673-6d9e-4812-bc5d-220e7908cc64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;turitop_booking_system_gift_voucher_recipient_email&quot;)</value>
      <webElementGuid>3b48588d-26cd-4c5a-9f47-7a36f597dddb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='turitop_booking_system_gift_voucher_recipient_email']</value>
      <webElementGuid>d067c7b8-078b-41c1-8a80-70d00ddc5319</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/input</value>
      <webElementGuid>c95e85d8-917a-47e0-9564-fb038c793c81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'turitop_booking_system_gift_voucher_recipient_email' and @id = 'turitop_booking_system_gift_voucher_recipient_email']</value>
      <webElementGuid>a3859940-f497-46f4-9204-b9af04babcbb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
